repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    entry: black --check --diff
    hooks:
      - id: black
        name: Black Formatter
        files: .
        language: python
        types: [ python ]
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: python manage.py makemigrations --dry-run --check --no-input
        language: system
        types: [ python ]
        files: ./backend/models.py
        pass_filenames: false
  - repo: local
    hooks:
      - id: pre-commit-djlint
        name: Djlint (html files)
        entry: djlint ./frontend/templates/ --profile django --reformat
        language: system
        files: ./frontend/templates/
        types: [ html ]
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
#      - id: name-tests-test   # (blocking)
#  - repo: https://github.com/asottile/setup-cfg-fmt
#    rev: v2.5.0
#    hooks:
#      - id: setup-cfg-fmt
#  - repo: https://github.com/asottile/pyupgrade
#    rev: v3.15.2
#    hooks:
#      - id: pyupgrade # (blocking)
#        args: [ --py39-plus ]
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.7.0
#    hooks:
#      - id: mypy # (blocking)
#        args:
#          - --explicit-package-bases
#          - --no-incremental
#    additional_dependencies: ['mypy >=1.7.0, <1.8.0']
