blank_issues_enabled: false
contact_links:
  - name: ğŸ” View Issues
    url: https://github.com/TreyWW/MyFinances/issues?q=is%3Aissue
    about: If you have found an issue (or a bug), try searching our issues tab before reporting it.
  - name: â“ Need some help
    url: https://github.com/TreyWW/MyFinances/discussions/categories/q-a
    about: If you have a question or are stuck setting up the project, open a Q&A discussion!
  - name: ğŸ“– View our documentation
    url: https://strelix.link/mfd/?utm_source=github_issue_create
    about: Check out our documentation to get started! We have lots of helpful info in there
