version: "3"

services:
  myfinances_django:
    restart: always
    build:
      context: ../../
      dockerfile: infrastructure/backend/Dockerfile
    ports:
      - '9012:9012'
    volumes:
      - ../../:/MyFinances
      - myfinances_static_volume:/mnt/static/
    networks:
      - myfinances_network
    env_file:
      - ../../env/MyFinances.env
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - '10012:10012'
    depends_on:
      - myfinances_django
    networks:
      - myfinances_network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - myfinances_static_volume:/srv/http/static/
      - ../nginx/default.conf:/etc/nginx/conf.d/myfinances.conf
    command: /bin/bash -c "nginx -g 'daemon off;'"
volumes:
  myfinances_static_volume:
networks:
  myfinances_network:
    driver: bridge
